#if defined(ESP_PLATFORM) || defined(PLM_MPEG_EMBEDDED)
#define PLM_BUFFER_DEFAULT_SIZE (4 * 1024)
#define PLM_AUDIO_BUFFER_DEFAULT_SIZE (1 * 1024)
#define PLM_AUDIO_BOUNDED_PACKET_STREAM 1
#define PLM_VIDEO_COMPACT_Y6_U5_V5
#define PLM_VIDEO_STREAMING_PICTURES
#ifndef PLM_MPEG_FAST_DCT_PREFIX
#define PLM_MPEG_FAST_DCT_PREFIX 1
#endif
#else
#define PLM_BUFFER_DEFAULT_SIZE (8 * 1024)
#ifndef PLM_MPEG_FAST_DCT_PREFIX
#define PLM_MPEG_FAST_DCT_PREFIX 0
#endif
#endif
#define PLM_VIDEO_MAX_FRAME_BYTES (320 * 240 * 3 / 2)
#define PL_MPEG_IMPLEMENTATION
#include "pl_mpeg.h"
