#ifndef HLV_BOARD_CONFIG_H
#define HLV_BOARD_CONFIG_H

#include "driver/gpio.h"

#define BOARD_TFT_SCK GPIO_NUM_14
#define BOARD_TFT_MOSI GPIO_NUM_13
#define BOARD_TFT_MISO GPIO_NUM_12
#define BOARD_TFT_CS GPIO_NUM_15
#define BOARD_TFT_DC GPIO_NUM_2
#define BOARD_TFT_BACKLIGHT GPIO_NUM_21

#define BOARD_SD_SCK GPIO_NUM_18
#define BOARD_SD_MOSI GPIO_NUM_23
#define BOARD_SD_MISO GPIO_NUM_19
#define BOARD_SD_CS GPIO_NUM_5

#define BOARD_AUDIO_PDM_DATA GPIO_NUM_26
#define BOARD_BOOT_BUTTON GPIO_NUM_0

#endif
